"""Deterministic static site generation.

Small explicit rendering functions, `html.escape` on every interpolated value,
relative URLs throughout, and no template package or CDN asset. Every page is
complete without JavaScript; the one script is progressive enhancement.
"""

from __future__ import annotations

import dataclasses
import html
import shutil
from pathlib import Path

from . import util
from .graph import EDGE_STYLE, DagView
from .model import Corpus, Dependencies, Work
from .util import Workspace


def esc(value: object) -> str:
    return html.escape("" if value is None else str(value), quote=True)


def rel(depth: int, target: str) -> str:
    """Relative URL from a page `depth` directories below the site root.

    Relative throughout so the same build works at localhost and under
    https://<owner>.github.io/<repository>/ without rewriting.
    """
    prefix = "../" * depth
    return (prefix + target.lstrip("/")) if target != "/" else (prefix or "./")


def work_href(depth: int, alias: str) -> str:
    return rel(depth, f"works/{util.safe_path_segment(alias)}/")


def node_href(depth: int, view: DagView, node_id: str) -> str:
    node = view.nodes.get(node_id)
    if node is not None and node.kind == "choice":
        return rel(depth, f"dependencies/#{util.safe_path_segment(node_id)}")
    return work_href(depth, node_id)


NAV = (
    ("", "Overview"),
    ("dependencies/", "Dependencies"),
    ("works/", "Works"),
    ("graph/", "Citation graph"),
    ("survey/", "Survey"),
    ("reports/", "Reports"),
)


def page(title: str, body: str, depth: int, *, subtitle: str = "",
         public: bool = False) -> str:
    nav = "".join(
        f'<a href="{esc(rel(depth, href) if href else rel(depth, "index.html"))}">{esc(label)}</a>'
        for href, label in NAV)
    build_label = "public build" if public else "local build"
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(title)} — bibgraph</title>
<link rel="stylesheet" href="{esc(rel(depth, 'site.css'))}">
</head>
<body>
<header class="site">
<nav aria-label="Main">{nav}</nav>
</header>
<main>
<h1>{esc(title)}</h1>
{f'<p class="muted">{esc(subtitle)}</p>' if subtitle else ''}
{body}
</main>
<footer class="site">
Generated by bibgraph {esc(util.GENERATOR_VERSION)} ({esc(build_label)}) at {esc(util.now_iso())}.
Computed observations are labelled separately from human interpretation.
</footer>
<script src="{esc(rel(depth, 'site.js'))}" defer></script>
</body>
</html>
"""


def badge(value: str, label: str | None = None) -> str:
    slug = util.safe_path_segment(str(value)).lower().replace(".", "-")
    return f'<span class="badge {esc(slug)}">{esc(label or value)}</span>'


def table(headers: list[str], rows: list[list[str]], empty: str = "None.") -> str:
    if not rows:
        return f'<p class="muted">{esc(empty)}</p>'
    head = "".join(f"<th scope=\"col\">{esc(h)}</th>" for h in headers)
    body = "".join("<tr>" + "".join(f"<td>{c}</td>" for c in row) + "</tr>" for row in rows)
    return f"<table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table>"


def definition_list(pairs: list[tuple[str, str]]) -> str:
    items = "".join(f"<dt>{esc(k)}</dt><dd>{v}</dd>" for k, v in pairs)
    return f"<dl>{items}</dl>"


# ---------------------------------------------------------------------------
# SVG
# ---------------------------------------------------------------------------


def render_dag_svg(view: DagView, depth: int, corpus: Corpus) -> str:
    """Deterministic inline SVG. Edge meaning is carried by dash and colour."""
    layout = view.layout()
    positions = layout["positions"]
    box_w, box_h = 168, 40
    alias_titles = {}
    by_id = corpus.by_id()
    for node_id, node in view.nodes.items():
        work = by_id.get(node.ref or "") or corpus.by_alias().get(node.ref or "")
        alias_titles[node_id] = work.display_title if work else node.label

    parts = [
        f'<svg class="dag" viewBox="0 0 {layout["width"]} {layout["height"]}" '
        f'width="{layout["width"]}" height="{layout["height"]}" role="img" '
        'aria-labelledby="dag-title dag-desc" xmlns="http://www.w3.org/2000/svg">',
        '<title id="dag-title">Dependency graph</title>',
        '<desc id="dag-desc">A typed directed acyclic graph. The same relationships '
        'are listed as text in the adjacency list below this diagram.</desc>',
        '<defs>',
    ]
    for edge_type, style in sorted(EDGE_STYLE.items()):
        parts.append(
            f'<marker id="arrow-{esc(edge_type)}" viewBox="0 0 10 10" refX="9" refY="5" '
            f'markerWidth="6" markerHeight="6" orient="auto-start-reverse">'
            f'<path d="M 0 0 L 10 5 L 0 10 z" fill="{esc(style["color"])}"/></marker>')
    parts.append("</defs>")

    for edge in sorted(view.edges, key=lambda e: (e.type, e.source, e.target)):
        if edge.source not in positions or edge.target not in positions:
            continue
        style = EDGE_STYLE.get(edge.type, EDGE_STYLE["prerequisite"])
        x1 = positions[edge.source]["x"] + box_w / 2
        y1 = positions[edge.source]["y"] + box_h
        x2 = positions[edge.target]["x"] + box_w / 2
        y2 = positions[edge.target]["y"]
        dash = f' stroke-dasharray="{esc(style["dash"])}"' if style["dash"] else ""
        parts.append(
            f'<line x1="{x1:.1f}" y1="{y1:.1f}" x2="{x2:.1f}" y2="{y2:.1f}" '
            f'stroke="{esc(style["color"])}" stroke-width="{style["width"]}"{dash} '
            f'marker-end="url(#arrow-{esc(edge.type)})">'
            f'<title>{esc(edge.source)} {esc(edge.type)} {esc(edge.target)}</title></line>')

    for node_id in sorted(positions):
        node = view.nodes[node_id]
        pos = positions[node_id]
        shape = ('rx="18"' if node.kind == "choice"
                 else 'rx="2"' if node.kind == "collection" else 'rx="6"')
        stroke = "#8a5a00" if node.kind == "choice" else "#1f4e79"
        dash = ' stroke-dasharray="4 2"' if node.kind == "choice" else ""
        label = node_id if len(node_id) <= 22 else node_id[:21] + "…"
        parts.append(
            f'<a href="{esc(node_href(depth, view, node_id))}">'
            # Filled with the page background so edges pass behind the label
            # rather than through it; the fill follows the colour scheme.
            f'<rect x="{pos["x"]}" y="{pos["y"]}" width="{box_w}" height="{box_h}" '
            f'{shape} fill="var(--bg, #ffffff)" stroke="{esc(stroke)}" '
            f'stroke-width="1.6"{dash}/>'
            f'<text x="{pos["x"] + 10}" y="{pos["y"] + 25}" fill="currentColor">'
            f'{esc(label)}</text>'
            f'<title>{esc(alias_titles.get(node_id, node_id))}</title></a>')
    parts.append("</svg>")
    return "\n".join(parts)


def render_legend() -> str:
    items = "".join(
        f'<li>{badge(t)} <span class="muted">stroke: '
        f'{esc(s["dash"] or "solid")}, colour {esc(s["color"])}</span></li>'
        for t, s in sorted(EDGE_STYLE.items()))
    return ('<h3>Edge types</h3><ul class="plain legend">' + items + "</ul>"
            '<p class="muted">Shape and dash pattern carry the same information as '
            'colour, so the diagram is readable without colour perception.</p>')


# ---------------------------------------------------------------------------
# Pages
# ---------------------------------------------------------------------------


@dataclasses.dataclass
class SiteData:
    corpus: Corpus
    deps: Dependencies
    profile: dict
    view: DagView
    artifacts: dict[str, dict]          # asset_id -> ledger row
    documents: dict[str, dict]          # work id -> extracted document
    analysis: dict | None = None
    survey: dict | None = None
    edges: list[dict] = dataclasses.field(default_factory=list)
    reviews: dict[str, dict] = dataclasses.field(default_factory=dict)
    public: bool = False


def build_index(data: SiteData) -> str:
    corpus, view = data.corpus, data.view
    unverified = [w for w in corpus.works if w.metadata_status == "unverified"]
    unresolved = [c for c in view.choices() if view.selection(c.id) is None]

    status_rows = []
    for work in sorted(corpus.works, key=lambda w: w.primary_alias):
        rows = [data.artifacts.get(a.id) for a in work.assets]
        downloaded = sum(1 for r in rows if r and r["status"] == "downloaded")
        doc = data.documents.get(work.id)
        status_rows.append([
            f'<a href="{esc(work_href(0, work.primary_alias))}">{esc(work.primary_alias)}</a>',
            esc(work.display_title),
            badge(work.work_type),
            badge(work.rights.access),
            badge(work.metadata_status),
            f"{downloaded}/{len(work.assets)}",
            badge(doc["overall_status"]) if doc else badge("not_extracted"),
        ])

    notice = ""
    if not corpus.source.get("supplied", False):
        notice = (
            '<div class="notice"><strong>Incomplete corpus.</strong> The source '
            'catalogue was not supplied, so every record below is a structural '
            'placeholder with no verified metadata. Nothing here has been invented '
            'to fill the gap.</div>')
    if not view.edges:
        notice += (
            '<div class="notice"><strong>Empty dependency graph.</strong> No typed '
            'edge has been recorded, so navigation cannot yet show prerequisites. '
            'The relationship diagram must be supplied and reviewed.</div>')

    choices_html = "".join(
        f'<li><a href="{esc(rel(0, "dependencies/#" + util.safe_path_segment(c.id)))}">'
        f'{esc(c.label)}</a> — {" or ".join(esc(o) for o in c.options)} '
        f'{badge("unresolved")}</li>' for c in unresolved)

    body = f"""
{notice}
<h2>Corpus status</h2>
{table(["Alias", "Title", "Type", "Access", "Metadata", "Acquired", "Extraction"], status_rows)}
<h2>Unresolved choices</h2>
{f'<ul class="plain">{choices_html}</ul>' if unresolved
 else '<p class="muted">Every alternative has been selected in the reading profile.</p>'}
<p class="muted">An unresolved choice is left unresolved. The reading order stops
at the choice and offers both branches rather than picking one.</p>
<h2>Reading profile</h2>
{definition_list([(k, esc(v) if v else '<em>unselected</em>')
                  for k, v in sorted(data.profile.items())] or [("(none)", "no choices defined")])}
<h2>Summary</h2>
{definition_list([
    ("Works", str(len(corpus.works))),
    ("Verified metadata", f"{len(corpus.works) - len(unverified)} of {len(corpus.works)}"),
    ("Dependency nodes", str(len(view.nodes))),
    ("Dependency edges", str(len(view.edges))),
    ("Assets declared", str(sum(len(w.assets) for w in corpus.works))),
    ("Assets downloaded", str(sum(1 for r in data.artifacts.values()
                                  if r["status"] == "downloaded"))),
])}
"""
    return page("Corpus overview", body, 0, public=data.public,
                subtitle="Local bibliography graph. Machine observations only; "
                         "reading judgement stays human.")


def build_dependencies(data: SiteData) -> str:
    view, corpus = data.view, data.corpus
    if view.edges:
        svg = render_dag_svg(view, 1, corpus)
    else:
        svg = ('<p class="empty">No dependency edge has been recorded, so there is '
               'no graph to draw. This is reported rather than rendered as an empty '
               'diagram that might be mistaken for a finished one.</p>')

    adjacency_rows = []
    for row in view.adjacency_text():
        prereqs = ", ".join(
            f'<a href="{esc(node_href(1, view, p["node"]))}">{esc(p["node"])}</a> '
            f'<span class="muted">({esc(p["type"])})</span>' for p in row["prerequisites"])
        dependents = ", ".join(
            f'<a href="{esc(node_href(1, view, d["node"]))}">{esc(d["node"])}</a> '
            f'<span class="muted">({esc(d["type"])})</span>' for d in row["dependents"])
        adjacency_rows.append([
            f'<a href="{esc(node_href(1, view, row["node"]))}">{esc(row["node"])}</a>',
            badge(row["kind"]),
            prereqs or '<span class="muted">none</span>',
            dependents or '<span class="muted">none</span>',
        ])

    try:
        order = view.reading_sequence()
        tree_rows = [
            [f'<a href="{esc(node_href(1, view, n))}">{esc(n)}</a>',
             str(view.layers().get(n, 0)),
             " &rsaquo; ".join(esc(p) for p in view.canonical_path(n))]
            for n in order]
    except ValueError as exc:
        tree_rows = []
        adjacency_rows.insert(0, [esc(str(exc)), "", "", ""])

    choice_sections = []
    for choice in view.choices():
        selected = view.selection(choice.id)
        branch_html = "".join(
            f"<li><a href=\"{esc(node_href(1, view, b.option))}\">{esc(b.option)}</a>"
            f"{' ' + badge('selected') if b.option == selected else ''}"
            f"<br><span class=\"muted\">unlocks: "
            f"{esc(', '.join(b.reachable) or 'nothing downstream')}</span></li>"
            for b in view.branches_for(choice.id))
        choice_sections.append(
            f'<section id="{esc(util.safe_path_segment(choice.id))}">'
            f"<h3>{esc(choice.label)} {badge('unresolved') if not selected else badge('resolved')}</h3>"
            f'<p class="muted">{esc(choice.note or "")}</p>'
            f'<ul class="plain">{branch_html}</ul>'
            f'<p class="muted">Select a branch by editing '
            f'<code>config/reading-profile.json</code>; the data model will not '
            f'choose one on your behalf.</p></section>')

    body = f"""
<h2>Typed graph</h2>
{svg}
{render_legend()}
<h2>Choices</h2>
{"".join(choice_sections) or '<p class="muted">No choice nodes.</p>'}
<h2>Tree projection and reading order</h2>
<p class="muted">A DAG node can have several parents, so the canonical path below
is one deterministic display path, not the only one. Each work page lists
<strong>all</strong> prerequisites separately.</p>
{table(["Node", "Depth", "Canonical path"], tree_rows)}
<h2>Adjacency list</h2>
<p class="muted">The same information as the diagram, in text.</p>
{table(["Node", "Kind", "Prerequisites", "Dependents"], adjacency_rows)}
"""
    return page("Dependencies", body, 1, public=data.public)


def build_works_index(data: SiteData) -> str:
    rows = []
    for work in sorted(data.corpus.works, key=lambda w: w.primary_alias):
        rows.append([
            f'<a href="{esc(work_href(1, work.primary_alias))}">{esc(work.primary_alias)}</a>',
            esc(work.display_title),
            badge(work.work_type),
            badge(work.rights.access),
            esc(", ".join(work.authors) or "—"),
            esc(work.year or "—"),
        ])
    body = f"<h2>All works</h2>{table(['Alias', 'Title', 'Type', 'Access', 'Authors', 'Year'], rows)}"
    return page("Works", body, 1, public=data.public)


KESHAV_TEMPLATE = {
    "pass_status": "unread",
    "five_cs": {"category": "", "context": "", "correctness": "",
                "contributions": "", "clarity": ""},
    "decision": {"continue": None, "reason": ""},
    "pass_two": {"figures": "", "evidence": "", "assumptions": "",
                 "unclear_terms": "", "important_references": ""},
    "pass_three": {"reconstructed_argument": "", "challenged_assumptions": "",
                   "weaknesses": "", "extensions": "", "reproducibility": ""},
}


def build_work_page(data: SiteData, work: Work) -> str:
    view = data.view
    alias = work.primary_alias
    depth = 2
    doc = data.documents.get(work.id)

    asset_rows = []
    for asset in work.assets:
        row = data.artifacts.get(asset.id)
        status = row["status"] if row else "not_requested"
        link = (f'<a href="{esc(asset.url)}" rel="noopener noreferrer">source</a>'
                if asset.url else '<span class="muted">—</span>')
        local = "—"
        if row and row["status"] == "downloaded" and not data.public:
            local = f'<code>{esc(row["path"])}</code>'
        elif row and row["status"] == "downloaded":
            local = '<span class="muted">held privately</span>'
        asset_rows.append([
            badge(asset.role), badge(asset.intent), badge(status), link, local,
            f'<code>{esc((row["sha256"] or "")[:12])}</code>' if row and row["sha256"] else "—",
            esc((row["reason"] or "") if row else ""),
        ])

    upstream = view.upstream(alias) if alias in view.nodes else []
    downstream = view.downstream(alias) if alias in view.nodes else []
    all_prereqs = view.all_prerequisites(alias) if alias in view.nodes else []
    alternatives = [e for e in (view.outgoing(alias) + view.incoming(alias))
                    if e.type in ("backup", "validates")] if alias in view.nodes else []

    def link_list(nodes: list[str]) -> str:
        if not nodes:
            return '<p class="muted">None.</p>'
        return ('<ul class="plain">' + "".join(
            f'<li><a href="{esc(node_href(depth, view, n))}">{esc(n)}</a></li>'
            for n in nodes) + "</ul>")

    choice = view.choice_for_option(alias) if alias in view.nodes else None
    choice_html = ""
    if choice is not None:
        others = [o for o in choice.options if o != alias]
        other_links = ", ".join(
            '<a href="%s">%s</a>' % (esc(work_href(depth, o)), esc(o)) for o in others)
        choice_link = esc(rel(depth, "dependencies/#" + util.safe_path_segment(choice.id)))
        unselected = ("Neither has been selected."
                      if view.selection(choice.id) is None else "")
        choice_html = (
            f'<div class="notice"><strong>Alternative.</strong> This work is one arm '
            f'of <a href="{choice_link}">{esc(choice.label)}</a>; the other '
            f'{"is" if len(others) == 1 else "are"} {other_links}. {unselected}</div>')

    previous, nxt = view.prev_next(alias) if alias in view.nodes else (None, None)
    pager = (
        '<nav class="pager" aria-label="Reading order">'
        + (f'<a href="{esc(node_href(depth, view, previous))}">&laquo; {esc(previous)}</a>'
           if previous else '<span class="muted">start of order</span>')
        + (f'<a href="{esc(node_href(depth, view, nxt))}">{esc(nxt)} &raquo;</a>'
           if nxt else '<span class="muted">end of order</span>')
        + "</nav>")

    extraction_html = render_extraction(doc, data.public) if doc else (
        '<p class="empty">Not extracted yet. No field is shown, because an absent '
        'value must never be displayed as an empty success.</p>')

    review = data.reviews.get(work.id, {}).get("payload") or KESHAV_TEMPLATE
    review_json = util.canonical_json({"work_id": work.id, "alias": alias, **review})
    area_id = f"review-{util.safe_path_segment(alias)}"
    review_html = f"""
<p class="muted">The machine performs the mechanical part of the first pass only.
The five Cs are your judgement, not an inference.</p>
<form method="post" action="#" onsubmit="return false">
<label for="{esc(area_id)}"><strong>Keshav review record (JSON)</strong></label>
<textarea id="{esc(area_id)}" name="review" spellcheck="false">{esc(review_json)}</textarea>
</form>
<p>
<button type="button" data-export-target="{esc(area_id)}"
        data-filename="{esc(alias)}.json" hidden>Download JSON</button>
<span class="muted">Select the text above and save it as
<code>annotations/{esc(alias)}.json</code>, then run
<code>bibgraph annotate {esc(alias)} annotations/{esc(alias)}.json</code>.
A download button appears if JavaScript is available; the copy-and-save route
works without it.</span>
</p>
"""

    rights_rows = [
        ("Access", badge(work.rights.access)),
        ("Licence", esc(work.rights.license or "not recorded")),
        ("Licence evidence",
         f'<a href="{esc(work.rights.license_evidence_url)}" rel="noopener noreferrer">evidence</a>'
         if work.rights.license_evidence_url else '<span class="muted">none recorded</span>'),
        ("Local storage", "permitted" if work.rights.local_storage_allowed else "not permitted"),
        ("Publish metadata", "yes" if work.rights.publish_metadata else "no"),
        ("Publish abstract", "yes" if work.rights.publish_abstract else "no"),
        ("Publish full text", "yes" if work.rights.publish_fulltext else "no"),
    ]

    body = f"""
{choice_html}
<h2>Citation</h2>
{definition_list([
    ("Alias", esc(alias)),
    ("Canonical id", f"<code>{esc(work.id)}</code>"),
    ("Title", esc(work.display_title)),
    ("Authors", esc("; ".join(work.authors) or "not recorded")),
    ("Year", esc(work.year or "not recorded")),
    ("Type", badge(work.work_type)),
    ("Metadata", badge(work.metadata_status)),
])}
<h2>Access and rights</h2>
{definition_list(rights_rows)}
<h2>Assets</h2>
{table(["Role", "Intent", "Status", "Source", "Local copy", "SHA-256", "Note"], asset_rows)}
<h2>Dependencies</h2>
<h3>Upstream prerequisites (direct)</h3>
{link_list(upstream)}
<h3>All prerequisites (transitive)</h3>
{link_list(all_prereqs)}
<h3>Downstream dependents (direct)</h3>
{link_list(downstream)}
<h3>Alternatives, backups and validations</h3>
{table(["From", "Type", "To"],
       [[f'<a href="{esc(node_href(depth, view, e.source))}">{esc(e.source)}</a>',
         badge(e.type),
         f'<a href="{esc(node_href(depth, view, e.target))}">{esc(e.target)}</a>']
        for e in alternatives])}
<h2>First-pass extraction</h2>
{extraction_html}
<h2>Keshav review</h2>
{review_html}
{pager}
"""
    return page(f"{alias} — {work.display_title}", body, depth, public=data.public)


def render_extraction(doc: dict, public: bool) -> str:
    """Render extracted fields, always with state, method, confidence and source."""
    rows = []
    for name in ("title", "abstract", "introduction", "conclusion", "references"):
        field = doc.get("fields", {}).get(name)
        if not field:
            rows.append([esc(name), badge("not_extracted"), "—", "—", "—"])
            continue
        status = field.get("status", "failed")
        showable = status == "present" and (not public or doc.get("publishable", {}).get(name))
        if showable:
            text = field.get("text") or ""
            preview = text if len(text) <= 600 else text[:600] + "…"
            shown = f"<details><summary>show</summary><pre>{esc(preview)}</pre></details>"
        elif status == "present":
            shown = '<span class="muted">held privately; not cleared for publication</span>'
        else:
            shown = f'<span class="muted">{esc(field.get("reason") or "no value")}</span>'
        source = field.get("source") or {}
        rows.append([
            esc(name),
            badge(status),
            f'{field.get("confidence", 0):.2f}' if field.get("confidence") is not None else "—",
            f'<code>{esc(field.get("method") or "—")}</code>',
            shown + (f'<br><span class="muted">pages {esc(source.get("pages"))}, '
                     f'sha {esc((source.get("asset_sha256") or "")[:12])}</span>'
                     if source else ""),
        ])

    sections = doc.get("sections") or []
    section_html = "".join(
        f'<li style="margin-left:{max(0, (s.get("level", 1) - 1)) * 1.2:.1f}rem">'
        f'{esc(s.get("number") or "")} {esc(s.get("title"))} '
        f'<span class="muted">(level {esc(s.get("level"))}, '
        f'confidence {s.get("confidence", 0):.2f})</span></li>' for s in sections)

    warnings = doc.get("warnings") or []
    warning_html = "".join(f"<li>{esc(w)}</li>" for w in warnings)

    return f"""
{definition_list([("Overall", badge(doc.get("overall_status", "unknown"))),
                  ("Adapter", f'<code>{esc(doc.get("adapter"))}</code>'),
                  ("Work type", badge(doc.get("work_type", "unknown")))])}
{table(["Field", "State", "Confidence", "Method", "Evidence"], rows)}
<h3>Section hierarchy</h3>
{f'<ul class="plain">{section_html}</ul>' if sections
 else '<p class="muted">No section tree was produced.</p>'}
<h3>Extraction warnings</h3>
{f"<ul>{warning_html}</ul>" if warnings else '<p class="muted">None.</p>'}
"""


def build_empty_state(title: str, explanation: str, depth: int, public: bool) -> str:
    return page(title, f'<p class="empty">{esc(explanation)}</p>', depth, public=public)


def build_reports_page(data: SiteData, reports: list[dict]) -> str:
    rows = []
    for report in reports:
        rows.append([
            esc(report.get("name")),
            esc(report.get("command")),
            esc(report.get("generated_at")),
            esc(report.get("summary")),
        ])
    body = f"""
<h2>Run reports</h2>
<p class="muted">Local filesystem paths, cache payloads and contact details are
removed from this view.</p>
{table(["Report", "Command", "Generated", "Summary"], rows,
       empty="No run has been recorded yet.")}
"""
    return page("Reports", body, 1, public=data.public)


# ---------------------------------------------------------------------------
# Builder
# ---------------------------------------------------------------------------


def load_site_data(ws: Workspace, corpus: Corpus, deps: Dependencies,
                   profile: dict, public: bool = False) -> SiteData:
    from .store import open_store

    artifacts: dict[str, dict] = {}
    reviews: dict[str, dict] = {}
    if ws.state_db.exists():
        with open_store(ws.state_db) as store:
            artifacts = {row["asset_id"]: row for row in store.artifacts()}
            reviews = store.reviews()

    documents: dict[str, dict] = {}
    if ws.documents.exists():
        for path in sorted(ws.documents.glob("*.json")):
            doc = util.read_json(path)
            documents[doc.get("work_id", path.stem)] = doc

    analysis = None
    analysis_path = ws.data / "analysis.json"
    if analysis_path.exists():
        analysis = util.read_json(analysis_path)

    survey = None
    survey_path = ws.data / "survey.json"
    if survey_path.exists():
        survey = util.read_json(survey_path)

    edges: list[dict] = []
    edges_path = ws.data / "edges.jsonl"
    if edges_path.exists():
        edges = [row for row in util.read_jsonl(edges_path) if "_meta" not in row]

    return SiteData(
        corpus=corpus, deps=deps, profile=profile, view=DagView(deps, profile),
        artifacts=artifacts, documents=documents, analysis=analysis,
        survey=survey, edges=edges, reviews=reviews, public=public,
    )


def build_site(ws: Workspace, data: SiteData, destination: Path) -> list[Path]:
    """Render the whole site. Returns every path written."""
    destination = Path(destination)
    if destination.exists():
        shutil.rmtree(destination)
    destination.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    def emit(relative: str, text: str) -> None:
        target = destination / relative
        util.write_text_atomic(target, text)
        written.append(target)

    emit("index.html", build_index(data))
    emit("dependencies/index.html", build_dependencies(data))
    emit("works/index.html", build_works_index(data))
    for work in data.corpus.works:
        emit(f"works/{util.safe_path_segment(work.primary_alias)}/index.html",
             build_work_page(data, work))

    if data.analysis and data.survey:
        from .survey import build_graph_page, build_survey_page

        emit("graph/index.html", build_graph_page(data))
        emit("survey/index.html", build_survey_page(data))
    else:
        emit("graph/index.html", build_empty_state(
            "Citation graph",
            "No resolved citation edge exists yet. Run extract and resolve first; "
            "an empty graph is reported as empty rather than drawn.",
            1, data.public))
        emit("survey/index.html", build_empty_state(
            "Survey",
            "No survey has been generated. The survey is derived from resolved "
            "references, so it stays empty until resolution has run.",
            1, data.public))

    emit("reports/index.html", build_reports_page(data, collect_report_summaries(ws)))

    for asset in ("site.css", "site.js"):
        source = resolve_site_asset(ws, asset)
        if source is None:
            raise FileNotFoundError(
                f"{asset} not found in {ws.site_src} or the packaged site-src; "
                "the site would render unstyled with broken links")
        util.write_text_atomic(destination / asset, source.read_text(encoding="utf-8"))
        written.append(destination / asset)

    manifest = {
        **util.derived_header({}, "build-site"),
        "public": data.public,
        "pages": sorted(str(p.relative_to(destination)) for p in written),
    }
    util.write_json_atomic(destination / "build-manifest.json", manifest)
    written.append(destination / "build-manifest.json")
    return written


def resolve_site_asset(ws: Workspace, name: str) -> Path | None:
    """Project site-src first, then the assets shipped beside the package.

    A project root that is not the repository root (a fixture, a separate
    corpus) still needs the stylesheet, so falling back is what makes the
    build work anywhere rather than silently emitting an unstyled site.
    """
    candidates = (ws.site_src / name, PACKAGED_SITE_SRC / name)
    return next((c for c in candidates if c.is_file()), None)


PACKAGED_SITE_SRC = Path(__file__).resolve().parents[2] / "site-src"


def collect_report_summaries(ws: Workspace) -> list[dict]:
    summaries = []
    if not ws.reports.exists():
        return summaries
    for path in sorted(ws.reports.glob("*.jsonl")):
        try:
            rows = util.read_jsonl(path)
        except (OSError, ValueError):
            continue
        if not rows:
            continue
        payload = rows[-1]
        summary = payload.get("summary") or {}
        if isinstance(summary, dict):
            text = ", ".join(f"{k}={v}" for k, v in summary.items()
                             if not isinstance(v, (dict, list)))
            counts = summary.get("counts")
            if isinstance(counts, dict):
                text = ", ".join(f"{k}={v}" for k, v in counts.items()) + (
                    f"; {text}" if text else "")
        else:
            text = ""
        summaries.append({
            "name": path.stem,
            "command": payload.get("command", ""),
            "generated_at": payload.get("generated_at", ""),
            "summary": text,
        })
    return summaries


# ---------------------------------------------------------------------------
# Publication allowlist
#
# An allowlist, not a denylist: the public build starts from nothing and copies
# in only what has been explicitly cleared. Open web access is not proof of
# redistribution permission, so an unknown licence publishes a citation and a
# link, never a copied document or extracted section.
# ---------------------------------------------------------------------------

# GitHub documents a 1 GB published-site ceiling. The default budget sits far
# below it because the right thing to publish is metadata and graphs, not a
# mirror of the bibliography.
DEFAULT_SIZE_BUDGET_BYTES = 100 * 1024 * 1024

PUBLISHABLE_TEXT_FIELDS = {
    "abstract": "publish_abstract",
    "introduction": "publish_fulltext",
    "conclusion": "publish_fulltext",
}


def clearance_for(work, field_name: str) -> tuple[bool, str]:
    """May this field's text be redistributed? Returns the decision and why."""
    rights = work.rights
    if field_name == "title":
        return (rights.publish_metadata,
                "publish_metadata" if rights.publish_metadata else "metadata withheld")
    if field_name == "references":
        return (rights.publish_metadata,
                "reference strings are metadata" if rights.publish_metadata
                else "metadata withheld")
    flag = PUBLISHABLE_TEXT_FIELDS.get(field_name)
    if flag is None:
        return False, "no publication policy for this field"
    if not getattr(rights, flag):
        return False, f"{flag}=false"
    if not rights.license_evidence_url:
        return False, f"{flag}=true but no licence evidence is recorded"
    return True, f"{flag}=true with licence evidence {rights.license_evidence_url}"


def apply_public_allowlist(data: SiteData) -> tuple[SiteData, dict]:
    """Strip everything not explicitly cleared, and report what survived."""
    by_id = data.corpus.by_id()
    included: list[dict] = []
    withheld: list[dict] = []

    documents: dict[str, dict] = {}
    for work_id, document in data.documents.items():
        work = by_id.get(work_id)
        if work is None:
            continue
        clean = {k: v for k, v in document.items() if k != "fields"}
        # Local paths and the private text layer never reach a public build.
        clean["source"] = None
        clean["hyphen_joins"] = []
        fields = {}
        publishable = {}
        for name, field in document.get("fields", {}).items():
            allowed, reason = clearance_for(work, name)
            publishable[name] = allowed
            copy = dict(field)
            if copy.get("source"):
                copy["source"] = {"asset_sha256": copy["source"].get("asset_sha256"),
                                  "pages": copy["source"].get("pages")}
            if not allowed and copy.get("text"):
                copy["text"] = None
                copy["reason"] = (copy.get("reason") or "") + \
                    f" (text withheld from the public build: {reason})"
            present = field.get("status") == "present"
            record = {"alias": work.primary_alias, "field": name,
                      "reason": reason if present
                      else f"nothing to publish: field is {field.get('status')}",
                      "license": work.rights.license,
                      "license_evidence_url": work.rights.license_evidence_url}
            (included if (allowed and present) else withheld).append(record)
            fields[name] = copy
        clean["fields"] = fields
        clean["publishable"] = publishable
        documents[work_id] = clean

    artifacts = {}
    for asset_id, row in data.artifacts.items():
        artifacts[asset_id] = {**row, "path": None}

    reviews = {}
    for work_id, review in data.reviews.items():
        payload = review.get("payload") or {}
        if payload.get("publish") is True:
            reviews[work_id] = review
        else:
            withheld.append({"alias": by_id.get(work_id).primary_alias
                             if work_id in by_id else work_id,
                             "field": "keshav_review", "license": None,
                             "license_evidence_url": None,
                             "reason": "private annotation: set \"publish\": true to "
                                       "include a note in the public build"})

    public_data = dataclasses.replace(
        data, documents=documents, artifacts=artifacts, reviews=reviews, public=True)
    report = {
        **util.derived_header({}, "build-site --public"),
        "included": sorted(included, key=lambda r: (r["alias"], r["field"])),
        "withheld": sorted(withheld, key=lambda r: (r["alias"], r["field"])),
        "counts": {"included": len(included), "withheld": len(withheld)},
    }
    return public_data, report


def render_publication_report(report: dict) -> str:
    lines = ["# Publication report", "", f"Generated: {util.now_iso()}", "",
             "Every full-text or abstract passage included in the public build is "
             "listed below with the licence evidence that permits it. An unknown "
             "licence publishes a citation and a link, never a copied document.",
             "", "## Included", "",
             "| Alias | Field | Licence | Evidence | Basis |",
             "| --- | --- | --- | --- | --- |"]
    if not report["included"]:
        lines.append("| _none_ | | | | |")
    for row in report["included"]:
        lines.append(f"| {row['alias']} | {row['field']} | {row['license'] or '—'} | "
                     f"{row['license_evidence_url'] or '—'} | {row['reason']} |")
    lines += ["", "## Withheld", "", "| Alias | Field | Reason |", "| --- | --- | --- |"]
    for row in report["withheld"]:
        lines.append(f"| {row['alias']} | {row['field']} | {row['reason']} |")
    return "\n".join(lines) + "\n"


def measure_size(root: Path) -> dict:
    files = [p for p in Path(root).rglob("*") if p.is_file()]
    total = sum(p.stat().st_size for p in files)
    largest = sorted(files, key=lambda p: -p.stat().st_size)[:5]
    return {
        "bytes": total,
        "files": len(files),
        "largest": [{"path": str(p.relative_to(root)), "bytes": p.stat().st_size}
                    for p in largest],
    }
